# Generated by Django 5.2.4 on 2025-07-18 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='factoryuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workvolume',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.factory'),
        ),
        migrations.AddConstraint(
            model_name='factoryuser',
            constraint=models.UniqueConstraint(fields=('user', 'factory'), name='unique_factory_user'),
        ),
    ]
